spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  # 指定 mapper.xml 文件位置,让 MyBatis 能正确找到并加载你写的所有 Mapper XML 文件，根据你的接口方法和 Mapper XML 文件自动关联。
  # 告诉 MyBatis 在项目的 classpath 路径下的 mapper 目录里，加载所有以 .xml 结尾的文件作为 Mapper 映射文件。
  mapper-locations: 
    classpath*:mapper/*.xml,
    classpath*:com/example/library/mapper/xml/*.xml
  # 开启驼峰命名映射（user_id → userId）
  configuration:
    map-underscore-to-camel-case: true